if savesign
    savepath = strcat(pathname(1:24), 'analysis_result.mat');
	save(savepath, ...
		'numstance', ...
		'dmdmat', ...
		'rt', ...
		'tt', ...
		'dt', ...
		'dmdmap', ...
		'lowfreq', ...
		'coordx', ...
		'coordy', ...
		'coordz', ...
		'nx', ...
		'ny', ...
		'nz', ...
		'-v7.3');
	savelist = {'visualization data', ...
		'number of instances', ...
		'rank of truncation', ...
		'total simulation time', ...
		'time step', ...
		'dmd data', ...
		'cut-off frequency', ...
		'x-coordinate', ...
		'y-coordinate', ...
		'z-coordinate', ...
		'x-dimension size', ...
		'y-dimension size', ...
		'z-dimension size'};
	for iter = 1:length(savelist)
		fprintf('save \t %s \n', savelist{iter});
	end
else
	% Do nothing
end
